#
# env
# * BUILD_TYPE
#   * Coverage
#   * Debug
#
sudo: required
dist: trusty
language: cpp
matrix:
  include:
    # for test coverage
    - os: linux
      compiler: gcc
      env:
        - BUILD_TYPE=Coverage
      addons:
        apt:
          packages:
            - lcov
    - os: linux
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            # List of whitelisted in travis packages for ubuntu-precise can be found here:
            #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
            # List of whitelisted in travis apt-sources:
            #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
            - ubuntu-toolchain-r-test
          packages:
            - libc6-i386
            - libc6-dbg
    - os: linux
      compiler: clang++
      env:
        - BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            # List of whitelisted in travis packages for ubuntu-precise can be found here:
            #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
            # List of whitelisted in travis apt-sources:
            #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
            - ubuntu-toolchain-r-test
          packages:
            - libc6-i386
            - libc6-dbg
    - os: osx
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
    - os: osx
      compiler: clang++
      # addons:
      env:
        - BUILD_TYPE=Debug
install:
  - ci/travis/install.sh
script:
  - ci/build/check_sanity.sh
  - ci/build/build.sh
after_success:
  - ci/travis/after_success.sh
notifications:
  email: false
