package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "quadrature",
    srcs = glob(
        ["*.cc"],
    ),
    copts = [
        "-std=c++11",
    ],
    deps = [
        "//recipe/quadrature",
    ],
)
